name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    environment: release

    permissions:
      contents: write
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTING=OFF
          cmake -S . -B build-nuget -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTING=OFF -DCPACK_GENERATOR=NuGet

      - name: Install
        run: |
            cmake --build build --target install
            cmake --build build-nuget --target install

      - name: Package (tgz, zip, deb, NuGet)
        run: |
          cpack -G TGZ --config .\build\CPackConfig.cmake
          cpack -G ZIP --config .\build\CPackConfig.cmake
          cpack -G DEB --config .\build\CPackConfig.cmake
          cpack -G NuGet --config .\build-nuget\CPackConfig.cmake

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          nuget push Cortado*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{steps.login.outputs.NUGET_API_KEY}}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Cortado*.tar.gz
            Cortado*.zip
            Cortado*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
